### ISSUE TITLE
Stop the REPL Server where there are still active connections.

### ISSUE THREAD

**Issue by bertlea** [iwanders/socketserverREPL#2]
I am running on Windows 7 Python3.6.  I found I cannot force the server to stop (quit) when there is still an active connection.  I tried Ctrl-C and Ctrl-Z.  Is there a way to force the server to stop other than kill the process?

BTW, thanks for the work! It is easy to start and runs nicely so far during my initial testing so far.

**Comment by iwanders** [comment]
Hi, I implemented your request in #3, you can now start it with `./socketserverREPL.py -k` to be able to close it even if there are active connections. Please let me know if this works for you on that PR.

It's good to hear that it works on windows as well, I had never tried that. Thanks for testing that functionality.

May I ask what you use it for? I still use it in combination with Pythonista, but I wonder if other people have found other good use cases for it, I'd be interested to hear about how you use it. Either way, I'm you posted this issue, as it means my code is being used by others :thumbsup:.

**Comment by bertlea** [comment]
Thank you very much for the quick response and a working solution!  The branch works perfectly as expected.  My usage for this is to share a local running Python instances with proprietary modules/API installed and linked to our financial information system to my colleagues.  It is over our internal network, so less security concerns.  Because we are a global company that our offices scattered around the world, using this socket Python allows everyone able to access the API without installing the system locally, not even Python.  All they need is to connect to my PC using ncat.
